name: main
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: [v*]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
          cache: pipenv
      - run: make deps
      - run: make test
